import discord
from discord import app_commands
from discord.ext import commands

class FunCommands(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    @app_commands.command(name="game_rps", description="Rock paper scissors")
    async def game_rps(self, interaction: discord.Interaction): await interaction.response.send_message("RPS.")
    @app_commands.command(name="game_dice", description="Roll a dice")
    async def game_dice(self, interaction: discord.Interaction): await interaction.response.send_message("Dice roll.")
    @app_commands.command(name="game_coin", description="Flip a coin")
    async def game_coin(self, interaction: discord.Interaction): await interaction.response.send_message("Coin flip.")
    @app_commands.command(name="game_guess", description="Guess a number")
    async def game_guess(self, interaction: discord.Interaction): await interaction.response.send_message("Guessing game.")
    @app_commands.command(name="game_trivia", description="Play trivia")
    async def game_trivia(self, interaction: discord.Interaction): await interaction.response.send_message("Trivia time.")
    @app_commands.command(name="meme_random", description="Get a random meme")
    async def meme_random(self, interaction: discord.Interaction): await interaction.response.send_message("Random meme.")
    @app_commands.command(name="meme_dank", description="Get a dank meme")
    async def meme_dank(self, interaction: discord.Interaction): await interaction.response.send_message("Dank meme.")
    @app_commands.command(name="meme_fresh", description="Get a fresh meme")
    async def meme_fresh(self, interaction: discord.Interaction): await interaction.response.send_message("Fresh meme.")
    @app_commands.command(name="meme_classic", description="Get a classic meme")
    async def meme_classic(self, interaction: discord.Interaction): await interaction.response.send_message("Classic meme.")
    @app_commands.command(name="meme_new", description="Get a new meme")
    async def meme_new(self, interaction: discord.Interaction): await interaction.response.send_message("New meme.")
    @app_commands.command(name="trivia_easy", description="Easy trivia")
    async def trivia_easy(self, interaction: discord.Interaction): await interaction.response.send_message("Easy trivia.")
    @app_commands.command(name="trivia_hard", description="Hard trivia")
    async def trivia_hard(self, interaction: discord.Interaction): await interaction.response.send_message("Hard trivia.")
    @app_commands.command(name="trivia_science", description="Science trivia")
    async def trivia_science(self, interaction: discord.Interaction): await interaction.response.send_message("Science trivia.")
    @app_commands.command(name="trivia_math", description="Math trivia")
    async def trivia_math(self, interaction: discord.Interaction): await interaction.response.send_message("Math trivia.")
    @app_commands.command(name="trivia_history", description="History trivia")
    async def trivia_history(self, interaction: discord.Interaction): await interaction.response.send_message("History trivia.")
    @app_commands.command(name="joke_dad", description="Dad joke")
    async def joke_dad(self, interaction: discord.Interaction): await interaction.response.send_message("Dad joke.")
    @app_commands.command(name="joke_yo", description="Yo mama joke")
    async def joke_yo(self, interaction: discord.Interaction): await interaction.response.send_message("Yo mama joke.")
    @app_commands.command(name="joke_dark", description="Dark joke")
    async def joke_dark(self, interaction: discord.Interaction): await interaction.response.send_message("Dark joke.")
    @app_commands.command(name="joke_pun", description="Pun")
    async def joke_pun(self, interaction: discord.Interaction): await interaction.response.send_message("Pun.")
    @app_commands.command(name="joke_knock", description="Knock knock joke")
    async def joke_knock(self, interaction: discord.Interaction): await interaction.response.send_message("Knock knock.")
    @app_commands.command(name="fun_8ball", description="8ball")
    async def fun_8ball(self, interaction: discord.Interaction): await interaction.response.send_message("8ball.")
    @app_commands.command(name="fun_slap", description="Slap")
    async def fun_slap(self, interaction: discord.Interaction): await interaction.response.send_message("Slap.")
    @app_commands.command(name="fun_hug", description="Hug")
    async def fun_hug(self, interaction: discord.Interaction): await interaction.response.send_message("Hug.")
    @app_commands.command(name="fun_kiss", description="Kiss")
    async def fun_kiss(self, interaction: discord.Interaction): await interaction.response.send_message("Kiss.")
    @app_commands.command(name="fun_poke", description="Poke")
    async def fun_poke(self, interaction: discord.Interaction): await interaction.response.send_message("Poke.")
    @app_commands.command(name="fun_pat", description="Pat")
    async def fun_pat(self, interaction: discord.Interaction): await interaction.response.send_message("Pat.")
    @app_commands.command(name="fun_dance", description="Dance")
    async def fun_dance(self, interaction: discord.Interaction): await interaction.response.send_message("Dance.")
    @app_commands.command(name="fun_sing", description="Sing")
    async def fun_sing(self, interaction: discord.Interaction): await interaction.response.send_message("Sing.")
    @app_commands.command(name="fun_jump", description="Jump")
    async def fun_jump(self, interaction: discord.Interaction): await interaction.response.send_message("Jump.")
    @app_commands.command(name="fun_run", description="Run")
    async def fun_run(self, interaction: discord.Interaction): await interaction.response.send_message("Run.")

async def setup(bot):
    await bot.add_cog(FunCommands(bot))
