import discord
from discord.ext import commands

class FunCommands(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    @commands.command(name="game_rps", help="Rock paper scissors")
    async def game_rps(self, ctx): await ctx.send("Rock paper scissors")
    @commands.command(name="game_dice", help="Roll a dice")
    async def game_dice(self, ctx): await ctx.send("Dice")
    @commands.command(name="game_coin", help="Flip a coin")
    async def game_coin(self, ctx): await ctx.send("Coin")
    @commands.command(name="game_guess", help="Guess a number")
    async def game_guess(self, ctx): await ctx.send("Guess")
    @commands.command(name="game_trivia", help="Play trivia")
    async def game_trivia(self, ctx): await ctx.send("Trivia")
    @commands.command(name="meme_random", help="Get a random meme")
    async def meme_random(self, ctx): await ctx.send("Meme")
    @commands.command(name="meme_dank", help="Get a dank meme")
    async def meme_dank(self, ctx): await ctx.send("Dank meme")
    @commands.command(name="meme_fresh", help="Get a fresh meme")
    async def meme_fresh(self, ctx): await ctx.send("Fresh meme")
    @commands.command(name="meme_classic", help="Get a classic meme")
    async def meme_classic(self, ctx): await ctx.send("Classic meme")
    @commands.command(name="meme_new", help="Get a new meme")
    async def meme_new(self, ctx): await ctx.send("New meme")
    @commands.command(name="trivia_easy", help="Easy trivia")
    async def trivia_easy(self, ctx): await ctx.send("Easy trivia")
    @commands.command(name="trivia_hard", help="Hard trivia")
    async def trivia_hard(self, ctx): await ctx.send("Hard trivia")
    @commands.command(name="trivia_science", help="Science trivia")
    async def trivia_science(self, ctx): await ctx.send("Science trivia")
    @commands.command(name="trivia_math", help="Math trivia")
    async def trivia_math(self, ctx): await ctx.send("Math trivia")
    @commands.command(name="trivia_history", help="History trivia")
    async def trivia_history(self, ctx): await ctx.send("History trivia")
    @commands.command(name="joke_dad", help="Dad joke")
    async def joke_dad(self, ctx): await ctx.send("Dad joke")
    @commands.command(name="joke_yo", help="Yo mama joke")
    async def joke_yo(self, ctx): await ctx.send("Yo mama joke")
    @commands.command(name="joke_dark", help="Dark joke")
    async def joke_dark(self, ctx): await ctx.send("Dark joke")
    @commands.command(name="joke_pun", help="Pun")
    async def joke_pun(self, ctx): await ctx.send("Pun")
    @commands.command(name="joke_knock", help="Knock knock joke")
    async def joke_knock(self, ctx): await ctx.send("Knock knock joke")
    @commands.command(name="fun_8ball", help="8ball")
    async def fun_8ball(self, ctx): await ctx.send("8ball")
    @commands.command(name="fun_slap", help="Slap")
    async def fun_slap(self, ctx): await ctx.send("Slap")
    @commands.command(name="fun_hug", help="Hug")
    async def fun_hug(self, ctx): await ctx.send("Hug")
    @commands.command(name="fun_kiss", help="Kiss")
    async def fun_kiss(self, ctx): await ctx.send("Kiss")
    @commands.command(name="fun_poke", help="Poke")
    async def fun_poke(self, ctx): await ctx.send("Poke")
    @commands.command(name="fun_pat", help="Pat")
    async def fun_pat(self, ctx): await ctx.send("Pat")
    @commands.command(name="fun_dance", help="Dance")
    async def fun_dance(self, ctx): await ctx.send("Dance")
    @commands.command(name="fun_sing", help="Sing")
    async def fun_sing(self, ctx): await ctx.send("Sing")
    @commands.command(name="fun_jump", help="Jump")
    async def fun_jump(self, ctx): await ctx.send("Jump")
    @commands.command(name="fun_run", help="Run")
    async def fun_run(self, ctx): await ctx.send("Run")

async def setup(bot):
    await bot.add_cog(FunCommands(bot))
